version: 2.1

jobs: 
  hello-world:
    docker: 
      - image: cimg/base:stable
    steps: 
      - checkout
      - run: echo " Hello, Circleci!"


workflows: 
  build: 
    jobs: 
      - hello-world