version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - run: npm install
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  test:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm test

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "Deploying app..." 
      # Here you’d run kubectl, terraform, or aws cli

workflows:
  ci_pipeline:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
